// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NonfungibleActivityManager$Type } from "./NonfungibleActivityManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NonfungibleActivityManager"]: NonfungibleActivityManager$Type;
    ["contracts/NonfungibleActivityManager.sol:NonfungibleActivityManager"]: NonfungibleActivityManager$Type;
  }

  interface ContractTypesMap {
    ["NonfungibleActivityManager"]: GetContractReturnType<NonfungibleActivityManager$Type["abi"]>;
    ["contracts/NonfungibleActivityManager.sol:NonfungibleActivityManager"]: GetContractReturnType<NonfungibleActivityManager$Type["abi"]>;
  }
}
