// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { TokenManager$Type } from "./TokenManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TokenManager"]: TokenManager$Type;
    ["contracts/TokenManager.sol:TokenManager"]: TokenManager$Type;
  }

  interface ContractTypesMap {
    ["TokenManager"]: GetContractReturnType<TokenManager$Type["abi"]>;
    ["contracts/TokenManager.sol:TokenManager"]: GetContractReturnType<TokenManager$Type["abi"]>;
  }
}
