/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export type { Erc20Permit } from './contracts/Erc20Permit'
export { Erc20Permit__factory } from './factories/contracts/Erc20Permit__factory'
